export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE';
export const CHANGE_ITEM_MARK = 'CHANGE_ITEM_MARK';
export const FILTER_CATEGORY = 'FILTER_CATEGORY';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SET_IMPORTANT_ITEM = 'SET_IMPORTANT_ITEM';
export const ADD_ITEM = 'ADD_ITEM';
export const ADD_ITEM_START = 'ADD_ITEM_START';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';
export const ADD_ITEM_TO_STATE = 'ADD_ITEM_TO_STATE';
export const ADD_ITEM_TO_DB = 'ADD_ITEM_TO_DB';

export const TASK_LIST_INIT = 'TASK_LIST_INIT';
export const SET_TASK = 'SET_TASK';
export const SET_TASK_FAIL = 'SET_TASK_FAIL';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INIT_LOGOUT = 'AUTH_INIT_LOGOUT';

export const CHECK_AUTH_STATE = 'CHECK_AUTH_STATE';
export const REDIRECT_PATH_AUTH = 'REDIRECT_PATH_AUTH';